import React from "react";
import Feature from "../Feature/Feature";
import SearchIcon from "../../assets/icons/web/3.svg";
import SelectIcon from "../../assets/icons/web/1.svg";
import StandOutIcon from "../../assets/icons/web/2.svg";

const FeatureTray = () => {
  return (
    <div className='bg-primary-blue bg-opacity-5 px-8 py-4 md:px-40 md:py-20'>
      <div className='flex flex-col md:grid md:grid-cols-3 gap-4'>
        <Feature
          title='Search'
          description='Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.'
          icon={SearchIcon}
        />
        <Feature
          title='Select'
          description='Choose from thousands of options generated by the slogan maker that fit your needs.'
          icon={SelectIcon}
        />
        <Feature
          title='Stand out'
          description="Congrats on your new slogan. It's time to win the world!"
          icon={StandOutIcon}
        />
      </div>
    </div>
  );
};

export default FeatureTray;
